QuizManager/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'QuizManager'
urlpatterns= [
    path('', views.index, name="index"),
    path('view_question/<int:id>/', views.view_question, name='view_question'),
    path('edit_question/<int:id>/', views.edit_question, name='edit_question'),
    path('delete_question/<int:id>/', views.delete_question, name='delete_question'),
    path('edit_choices/<int:id>/', views.edit_choices, name='edit_choices'),
    path('add_question/<str:quiz>/', views.add_question, name='add_question'),
    path('add_quiz', views.add_quiz, name='add_quiz'),
    path('view_quiz/<int:id>/', views.view_quiz, name='view_quiz'),
    path('view_quizzes', views.view_quizzes, name='view_quizzes'),
    path('edit_quiz/<int:id>/', views.edit_quiz, name='edit_quiz'),
    path('delete_quiz/<int:id>/', views.delete_quiz, name='delete_quiz'),
    path('take_quiz/<int:id>/', views.take_quiz, name='take_quiz'),
    path('quiz_results/<int:id>/', views.quiz_results, name='quiz_results'),
    path('view_assigned_quizzes', views.view_assigned_quizzes, name='view_assigned_quizzes'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('admin', admin.site.urls)
]

synoptic/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('QuizManager/', include('QuizManager.urls', namespace='QuizManager')),
]

QuizManager/models.py
from django.db import models

from django.contrib.auth import get_user_model


class Quiz(models.Model):
    quiz_name = models.CharField(max_length=30)
    assigned_users = models.ManyToManyField(
        get_user_model(),
        blank=True,
        related_name="assigned_quizzes"
        )
    def __str__(self):
        return self.quiz_name

class Question(models.Model):
    quiz = models.ForeignKey(
        Quiz, 
        on_delete=models.CASCADE,
        related_name='questions'
        )
    question_text = models.CharField(max_length=300)
    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(
        Question,
        on_delete=models.CASCADE,
        related_name="choices"
    )
    choice_text = models.CharField(max_length=300)
    correct = models.BooleanField()
    def __str__(self):
        return self.choice_text

class Result(models.Model):
    quiz = models.ForeignKey(
        Quiz,
        on_delete=models.CASCADE,
        related_name="quiz"
    )
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )
    score = models.IntegerField()

    def __str__(self):
        return str(self.score)
    

QuizManager/forms.py
from django import forms

from django.forms import ModelForm

from django.contrib.auth.forms import AuthenticationForm
from django.forms.models import modelform_factory, inlineformset_factory

from .models import Question, Quiz, Choice

class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        for field in ('username', 'password'):
            self.fields[field].widget.attrs = {'class' : 'form-control'}


class QuestionModelForm(ModelForm):
    class Meta:
        model = Question
        fields = '__all__'

class QuizModelForm(ModelForm):
    class Meta:
        model = Quiz
        fields = '__all__'

class AnswerQuestionForm(forms.Form):
    choices = forms.ModelMultipleChoiceField(queryset=None, label=None)

    def __init__(self, question, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['choices'].queryset = question.choices.all()
        self.fields['choices'].label = question.question_text

QuestionChoiceFormset = inlineformset_factory(Question, Choice, fields=('choice_text', 'correct'), max_num=4, extra=4)

QuizManager/views.py
from django.shortcuts import redirect, render, get_object_or_404

from django.http import HttpResponse, HttpResponseRedirect

from django.contrib import messages

from django.contrib.auth import login as auth_login
from django.contrib.auth import authenticate as auth_authenticate
from django.contrib.auth import logout as auth_logout

from .models import Choice, Question, Quiz, Result

from .forms import QuizModelForm, UserLoginForm, QuestionChoiceFormset, QuestionModelForm, AnswerQuestionForm


def index(request):
    if not request.user.is_authenticated:
        return redirect('QuizManager:login')
    quizzes = Quiz.objects.all()
    context = {
        'quizzes' : quizzes
    }
    return render(request, 'QuizManager/index.html', context)

def view_quizzes(request):
    quizzes = Quiz.objects.all()
    context = {
        'quizzes' : quizzes
    }
    return render(request, 'QuizManager/view_quizzes.html', context)


def edit_question(request, id):
    question = get_object_or_404(Question, pk=id)
    form = QuestionModelForm(request.POST or None,instance=question)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('QuizManager:view_question', id=id)
    context = {
        'form' : form,
        'question' : question,
        'id' : id
    }
    return render(request, 'QuizManager/edit_question.html', context)

def view_question(request, id):
    question = get_object_or_404(Question, pk=id)
    quiz_id = question.quiz.id
    context = {
        'question' : question,
        'quiz_id' : quiz_id
    }
    return render(request, 'QuizManager/view_question.html', context)

def edit_choices(request, id):
    question = get_object_or_404(Question, pk=id)
    formset = QuestionChoiceFormset(instance=question)
    if request.method == 'POST':
        formset = QuestionChoiceFormset(request.POST, instance=question)
        if formset.is_valid():
            formset.save()
            return redirect('QuizManager:view_question', id=id)
    context = {
        'question' : question,
        'formset' : formset,
        'id' : id
    }
    return render(request, 'QuizManager/edit_choices.html', context)

def add_question(request, quiz=None):
    if request.method == 'POST':
        form = QuestionModelForm(request.POST)
        if form.is_valid():
            question = form.save()
            return redirect('QuizManager:view_question', id=question.id)
    elif quiz:
        initial_quiz = get_object_or_404(Quiz, pk=quiz)
        form = QuestionModelForm(initial={'quiz' : quiz })
    else:
        form = QuestionModelForm()
    context = {
        'form' : form
    }
    return render(request, 'QuizManager/add_question.html', context)

def delete_question(request, id):
    question = get_object_or_404(Question, pk=id)
    quiz = question.quiz.id
    question.delete()
    return redirect('QuizManager:view_quiz', id=quiz)

def add_quiz(request):
    if request.method == 'POST':
        form = QuizModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('QuizManager:view_quizzes')
    else:
        form = QuizModelForm
    context = {
        'form' : form
    }
    return render(request, 'QuizManager/add_quiz.html', context)

def view_quiz(request, id):
    quiz = get_object_or_404(Quiz, pk=id)
    questions = quiz.questions.all()
    context = {
        'quiz' : quiz,
        'questions' : questions
    }
    return render(request, 'QuizManager/view_quiz.html', context)

def edit_quiz(request, id):
    quiz = get_object_or_404(Quiz, pk=id)
    form = QuizModelForm(request.POST or None,instance=quiz)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('QuizManager:view_quiz', id=quiz.id)
    context = {
        'quiz' : quiz,
        'form' : form,
    }
    return render(request, 'QuizManager/edit_quiz.html', context)

def delete_quiz(request, id):
    quiz = get_object_or_404(Quiz, pk=id)
    quiz.delete()
    return redirect('QuizManager:view_quizzes')

def take_quiz(request, id):
    quiz = get_object_or_404(Quiz, pk=id)
    if request.method == 'POST':
        choices = request.POST.getlist('choices')
        score = 0
        for choice in choices:
            choice_object = Choice.objects.get(pk=int(choice))
            if choice_object.correct:
                score += 1
        result_obj = Result(quiz=quiz, user=request.user, score=score)
        result_obj.save()
        request.user.assigned_quizzes.remove(quiz)
        return redirect('QuizManager:quiz_results', id=result_obj.pk)
    questions = quiz.questions.all()
    forms = [AnswerQuestionForm(question) for question in questions]
    context = {
        'quiz' : quiz,
        'questions' : questions,
        'forms' : forms
    }
    return render(request, 'QuizManager/take_quiz.html', context)

def quiz_results(request, id):
    result = get_object_or_404(Result, pk=id)
    max_score = result.quiz.questions.count()
    context = {
        'max_score' : max_score,
        'result' : result
    }
    return render(request, 'QuizManager/quiz_results.html', context)


def view_assigned_quizzes(request):
    assigned_quizzes = request.user.assigned_quizzes.all()
    context = {
        'assigned_quizzes' : assigned_quizzes
    }
    return render(request, 'QuizManager/view_assigned_quizzes.html', context)

def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data = request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = auth_authenticate(username=username, password=password)
            if user is not None:
                auth_login(request, user)
                return redirect('QuizManager:index')
            else:
                messages.error(request, "Invalid credentials")
        else:
            messages.error(request, "Invalid credentials")
    else:
        form = UserLoginForm()
    context ={
        'form' : form
    }
    return render(request,"QuizManager/login.html", context)

def logout(request):
    auth_logout(request)
    return redirect('QuizManager:login')

QuizManager/templates/QuizManager/add_question.html
{% extends 'QuizManager/base.html' %}
{% block title %}Add Question{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-sm-6 mx-auto">
        <form action="" method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <button class="btn btn-primary btn-lg btn-block" type="submit">Submit</button>
        </form>
    </div>
</div>
{% endblock %}

QuizManager/templates/QuizManager/add_quiz.html
{% extends 'QuizManager/base.html' %}
{% block title %}Add Quiz{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-sm-6 mx-auto">
        <form action="" method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <button class="btn btn-primary btn-lg btn-block" type="submit">Submit</button>
        </form>
    </div>
</div>
{% endblock %}

QuizManager/templates/QuizManager/base.html
<!DOCTYPE html>

<html>
    <head>
        <title> {% block title %}Home {% endblock title %} | Quiz Manager</title>
        {% load static %}
        {% block head_favicon %}
            <link rel="icon" type="image/png"
                  href="{{ static }}images/favicon.ico">
        {% endblock head_favicon %}
        {% block head_meta %}
            {% block head_meta_charset %}
                <meta http-equiv="Content-Type"
                      content="text/html; charset=utf-8" />
            {% endblock head_meta_charset %}
            {% block head_meta_contentlanguage %}
                <meta http-equiv="Content-Language" value="en-US" />
            {% endblock head_meta_contentlanguage %}
            {% block head_meta_viewport %}
                <meta name="viewport"
                      content="width=device-width, initial-scale=1.0">
            {% endblock head_meta_viewport %}
        {% endblock head_meta %}
        {% block head_css %}
            {% block head_css_site %}
                <link href="{% static 'QuizManager/css/bootstrap.min.css' %}"
                      rel="stylesheet" media="screen">
                <link href="{% static 'QuizManager/css/main.css' %}"
                      rel="stylesheet" media="screen">
            {% endblock head_css_site %}
            {% block head_css_section %}{% endblock head_css_section %}
            {% block head_css_page %}{% endblock head_css_page %}
        {% endblock head_css %}
    </head>
    <body>
        {% block navbar %}
        <!--Navbar Starts Here-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
            <a class="navbar-brand" href="javascript:void(0)">
                Quiz Manager
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'QuizManager:index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                </ul>
                {% if user.is_authenticated %}
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{user.username}}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'QuizManager:logout' %}">Logout</a>
                    </div>
                    </li>
                </ul>
                {% endif %}
            </div>
        </nav>
        {% endblock navbar %}
        
        <!--Navbar Ends-->
        {# The Document Body #}
        <div class="container-fluid">
            {% block content %}
                if you see this, something is wrong!
            {% endblock content %}
        </div>
        {# The Footer #}
    </body>
    {# Set of blocks that can be used to display JavaScript files #}
    {% block footer_javascript %}
        {% block footer_javascript_site %}
            <script src="{% static 'QuizManager/js/jquery-3.5.1.min.js'%}"></script>
            <script src="{% static 'QuizManager/js/bootstrap.min.js'%}"></script>
        {% endblock footer_javascript_site %}
        {% block footer_javascript_section %}{% endblock footer_javascript_section %}
        {% block footer_javascript_page %}{% endblock footer_javascript_page %}
    {% endblock footer_javascript %}
</html>
</html>

QuizManager/templates/QuizManager/edit_choices.html
{% extends 'QuizManager/base.html' %}
{% block title %}Add Question{% endblock %}
{% block content %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-sm-6 mx-auto">
        <h3>Question text: {{question.question_text}}</h3>
        <form action="{% url 'QuizManager:edit_choices' id %}" method="POST">
            {% csrf_token %}
            {{ formset.management_form }}
            {% for form in formset %}
                {{form|crispy}}
            {% endfor %}
            <button class="btn btn-primary btn-lg btn-block" type="submit">Submit</button>
        </form>
    </div>
</div>
{% endblock %}

QuizManager/templates/QuizManager/edit_question.html
{% extends 'QuizManager/base.html' %}
{% block title %}Edit Question{% endblock %}
{% block content %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-sm-6 mx-auto">
        <form action="{% url 'QuizManager:edit_question' id=question.id %}" method="post" class="m-3">
            {% csrf_token %}
            {{form|crispy}}
            <button class="btn btn-primary btn-lg btn-block" type="submit">Submit</button>
        </form>
    </div>
</div>
{% endblock %}

QuizManager/templates/QuizManager/edit_quiz.html
{% extends 'QuizManager/base.html' %}
{% block title %}Edit Quiz{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-sm-6 mx-auto">
        <form action="" method="post" class="m-3">
            {% csrf_token %}
            {{form|crispy}}
            <button class="btn btn-primary btn-lg btn-block" type="submit">Submit</button>
        </form>
    </div>
</div>
{% endblock %}

QuizManager/templates/QuizManager/index.html
{% extends 'QuizManager/base.html' %}
{% block title%} Home {%endblock%}
{% block content %}
<div class='row'>
    <div class='col-6 mx-auto'>
        {% if perms.QuizManager.view_quiz %}
        <a href="{% url 'QuizManager:view_quizzes' %}" class="btn btn-primary btn-lg  btn-block p-5">Teacher Portal</a>
        {% endif %}
        <a href="{% url 'QuizManager:view_assigned_quizzes' %}" class="btn btn-primary btn-lg  btn-block p-5">Student Portal</a>
    </div>
</div>
{% endblock %}

QuizManager/templates/QuizManager/login.html
{% extends 'QuizManager/base.html' %}
{% block title %}Login{% endblock %}
{% block navbar %}
{% endblock %}
{% block content %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-sm-3 mx-auto">
    <h2 class="text-center">Sign in</h2>
        <form method="post" action="{% url 'QuizManager:login' %}">
        {% csrf_token %}
        {{form|crispy}}
        <button class="btn btn-primary btn-lg btn-block" type="submit">Login</button>
        </form>
        {% for message in messages %}
        <div class="alert alert-danger" style="display:inline-block;">
            <a class="close" href="#" data-dismiss="alert">×</a>
            {{ message }}
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

QuizManager/templates/QuizManager/quiz_results.html
{% extends 'QuizManager/base.html' %}
{% block title %}Quiz Results{% endblock %}
{% block content %}
<div class="row">
    <div class="col-sm-4 mx-auto">
        <ul class="list-group">
            <li class="list-group-item text-center">{{result.quiz}}</li>
            <li class="list-group-item text-center">{{result.score}} / {{max_score}}</li>
            <a href="{% url 'QuizManager:view_assigned_quizzes' %}" class="btn btn-primary btn-lg  btn-block">Back to assigned quizzes</a>
        </ul>
    </div>
</div>
{% endblock %}

QuizManager/templates/QuizManager/take_quiz.html
{% extends 'QuizManager/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block head_css_page %} 
<link href="{% static 'QuizManager/css/take_quiz.css' %}" rel="stylesheet" media="screen">
{% endblock %}
{% block title %}Take Quiz{% endblock %}
{% block content %}
<div class="row">
    <div class="col-6 mx-auto">
        <h1 class="text-center">{{quiz}}</h1>
        <form action="" method="post" class="m-3">
            {% csrf_token %}
            {% for form in forms %}
                {{form|crispy}}
            {% endfor %}
            <button class="btn btn-primary btn-lg btn-block" type="submit">Submit Answers</button>
        </form>
    </div>
</div>
{% endblock %}
{% block footer_javascript_page %}
<script>
    $(".selectmultiple").each(function () {
        var options = $(this).children('option');
        $(options).each(function () {
            var initial_index = Math.floor(options.length * (Math.random() % 1));
            var swapped_index = Math.floor(options.length * (Math.random() % 1));
            var initial_text = options[initial_index]['text']
            var initial_value = options[initial_index]['value']
            options[initial_index]['text'] = options[swapped_index]['text']
            options[initial_index]['value'] = options[swapped_index]['value']
            options[swapped_index]['text'] = initial_text
            options[swapped_index]['value'] = initial_value
        })
    });

</script>
{% endblock footer_javascript_page %}

QuizManager/templates/QuizManager/view_assigned_quizzes.html
{% extends 'QuizManager/base.html' %}
{% block title%} View Assigned Quizzes {% endblock %}
{% block content %}
<div class="row">
    <div class="col col-sm-4 mx-auto">
        <h1 class="text-center">Assigned Quizzes</h1>
        {% for quiz in assigned_quizzes %}
        <a href="{% url 'QuizManager:take_quiz' id=quiz.id %}" class="btn btn-primary btn-lg btn-block" role="button" aria-disabled="true">{{quiz}}</a>
        {% endfor %}
    </div>
</div>
{% endblock %}

QuizManager/templates/QuizManager/view_question.html
{% extends 'QuizManager/base.html' %}
{% block title %}View Question{% endblock %}
{% block content %}
<div class="row">
    <div class="col-sm-4 mx-auto">
        <ul class="list-group mb-2">
            <li class="list-group-item text-center">{{question.question_text}}</li>
            {% for choice in question.choices.all %}
            <li class="list-group-item text-center {% if choice.correct %}bg-success{% else %}bg-danger{% endif %}">{{choice.choice_text}}</li>
            {% endfor %}
        </ul>
        {% if perms.QuizManager.change_question %}
        <a href="{% url 'QuizManager:edit_choices' id=question.id %}" class="btn btn-primary btn-lg btn-block" role="button" aria-disabled="true">Edit Choices</a>
        <a href="{% url 'QuizManager:edit_question' id=question.id %}" class="btn btn-primary btn-lg btn-block" role="button" aria-disabled="true">Edit Question</a>
        <button type="button" class="btn btn-danger btn-lg btn-block" data-toggle="modal" data-target="#confirmDeleteQuestion">
            Delete Question
        </button>
        {% endif %}
        <a href="{% url 'QuizManager:view_quiz' id=quiz_id %}" class="btn btn-primary btn-lg btn-block" role="button" aria-disabled="true">Back To Quiz</a> 
    </div>
</div>
<div class="modal fade" id="confirmDeleteQuestion" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
            Are you sure you want to delete this Quiz?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary btn-lg btn-block" data-dismiss="modal">Cancel</button>
          <a href="{% url 'QuizManager:delete_question' id=question.id %}" class="btn btn-danger btn-lg btn-block" role="button" aria-disabled="true">Delete Question</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

QuizManager/templates/QuizManager/view_quiz.html
{% extends 'QuizManager/base.html' %}
{% block title %}View Quiz{% endblock %}
{% block content %}
<div class='row'>
    <div class='col-6 mx-auto'>
        <h1 class='text-center'>{{quiz.quiz_name}}</h1>
        <div class='list-group'>
            {% for question in questions %}
            <a href="{% url 'QuizManager:view_question' question.id %}" class="list-group-item list-group-item-action text-center">{{question.question_text}}</a>
            {% endfor %}
            <br>
            <a href="{% url 'QuizManager:add_question' quiz=quiz.id %}" class="btn btn-primary btn-lg btn-block" role="button" aria-disabled="true">Add Question</a>
            {% if perms.QuizManager.change_quiz %}
            <a href="{% url 'QuizManager:edit_quiz' id=quiz.id %}" class="btn btn-primary btn-lg btn-block" role="button" aria-disabled="true">Edit Quiz</a>
            <button type="button" class="btn btn-danger btn-lg btn-block" data-toggle="modal" data-target="#confirmDeleteQuiz">
                Delete Quiz
            </button>
            {% endif %}
            <a href="{% url 'QuizManager:view_quizzes' %}" class="btn btn-primary btn-lg btn-block" role="button" aria-disabled="true">Back To Quizzes</a>
        </div>
    </div>
</div>
<div class="modal fade" id="confirmDeleteQuiz" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
            Are you sure you want to delete this Quiz?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary btn-lg btn-block" data-dismiss="modal">Cancel</button>
          <a href="{% url 'QuizManager:delete_quiz' id=quiz.id %}" class="btn btn-danger btn-lg btn-block" role="button" aria-disabled="true">Delete Quiz</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

QuizManager/templates/QuizManager/view_quizzes.html
{% extends 'QuizManager/base.html' %}
{% block title%} View Quizzes {%endblock%}
{% block content %}
<div class='row'>
    <div class='col-6 mx-auto'>
        <div class='list-group'>
            {% for quiz in quizzes %}
            <a href="{% url 'QuizManager:view_quiz' quiz.id %}" class="list-group-item list-group-item-action text-center">{{quiz.quiz_name}}</a>
            {% endfor %}
        </div>
        <br>
        <a href="{% url 'QuizManager:add_quiz' %}" class="btn btn-primary btn-lg btn-block">Add Quiz</a>
    </div>
</div>
{% endblock %}